[package]
name = "hcl2json"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hcl2json"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
hcl-rs = "0.16"
serde_json = "1.0"
anyhow = "1.0"

[dev-dependencies]
tempfile = "3.0"
